### PR TITLE
Feature/nodetypeservlet

### PR DESCRIPTION
**Pull request by stoerr**
This is for https://github.com/ist-dresden/composum/issues/199 : since he already provided the crucial code and the rest was mostly copy and paste, and since I had wished for something like that already several times, too, I quickly whipped up an implementation.

This contains a NodeTypeServlet at /bin/cpm/nodes/debug/nodetypes which exports the nodetypes in the usual nodetypes.cnd format, optionally restricted by a regex parameter nameregex for the type name. And I also put basically the same thing into a new Sling webconsole plugin.

I also moved most of the current Composum webconsole plugins to console, since I think they rather belong there instead of core-commons. I just left the clientlib plugin there since I feel it rather belongs to the other clientlib stuff, and since it needs an admin resolver which is currently allowed in commons but not in console.

When it's approved, I volunteer to do the merge to 2.0 since that needs some OSGI 6 changes.

### CODE REVIEW

**Comment by stoerr** [comment]
Since you asked so nicely :-) and even provided the crucial code yourself, I whipped up a quick implementation for that. If you want to try it out - it's currently at branch https://github.com/ist-dresden/composum/tree/feature/nodetypeservlet  . It's URL is /bin/cpm/nodes/debug/nodetypes and has an optional nameregex parameter where you can restrict the types if you need to - since you don't it's fine if you skip it and thus get everything. Please notice that this is subject to code review by my boss, so there might be some changes, especially the URL. I also provided it in form of a console plugin, since that was the form in which I had wished for it sometimes.

**Comment by stoerr** [comment]
For the record: just some ideas what could be extended in the future, if that'd be needed. 
- It could be given a resource path (or even a resource tree) and print just the nodetypes which are relevant. Possibly even the effective nodetype (not sure whether this works or even makes sense).
- If we also do it by resource, it would be a candidate for a new tab in the browser.
- Sometimes the ability to import would be nice, too.

**Comment by pun-ky** [comment]
But why are you wrapping these contents into HTML tags... I need pure contents. If you will do this that way, I will need to implement extracting contents between tags :/

**Comment by stoerr** [comment]
@pun-ky which URL did you use? The URL /bin/cpm/nodes/debug/nodetypes should not give any HTML tags. /system/console/nodetypes wraps it of course, because it's in the console meant for the browser. But I'm not quite sure what you mean.

**Comment by pun-ky** [comment]
Ok fine then. Thanks

**Pull request merged**
